# fly.toml app configuration file generated for fehrm-datingapp on 2023-08-02T10:14:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fehrm-datingapp"
primary_region = "arn"

[build]
  image = "fehrmfehrm/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dlyhdxoqu"
  CloudinarySettings__ApiKey="367165887667189"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
